### ISSUE TITLE
Realizar classificação com o algoritmo SVM

### ISSUE THREAD

**Issue by MackMendes** [a-n-d-r-e-i/text-mining#4]
Realizar classificação binária (Spam ou não-Spam) utilizando o algoritmo SVM.

**Comment by 92amartins** [comment]
@MackMendes Esse daí já deu quase bão! Lembre-se de tirar o SVM do `main.R` e jogar dentro de `model`

**Comment by MackMendes** [comment]
Finalizado man?

**Comment by MackMendes** [comment]
@a-n-d-r-e-i

**Comment by 92amartins** [comment]
Parece ótimo!
